- name: create the data directory
  file: path=/data state=directory mode=777
  tags:
    - ebs

- name: Set filesystem
  command: "mkfs.ext4 {{ data_volume_name | default('/dev/xvdh') }}"
  tags:
    - ebs

- name: Mount EBS volume
  command: "mount -t ext4 {{ data_volume_name | default('/dev/xvdh') }} /data"
  tags:
    - ebs

- name: Setup mounts on restart
  mount: name=/data src="{{ data_volume_name | default('/dev/xvdh') }}" fstype=ext4 state=present
  tags:
    - ebs
    - ebs_mount