- name: Setup namematching package
  ansible.builtin.debconf:
    name: ala-namematching-service
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: string
  with_items:
  - {
    question: "ala-namematching-service/source",
    value: "{{ ala_namemaching_service_source | default('https://archives.ala.org.au/archives/nameindexes/20210811/namematching-20210811.tgz') }}"
    }
  - {
    question: "ala-namematching-service/sha1",
    value: "{{ ala_namemaching_service_source_sha1 | default('563814a7b5d886b746e10eb40c44f0d9bda62371') }}"
    }
  when: use_docker_with_pipelines is defined and use_docker_with_pipelines | bool == False
  tags:
    - apt

# NBN - if NBN version we want to install the underlying ala apt package first
- name: Install ala-namematching-service version {{ ala_namematching_service_version }}
  apt:
    name:
      - ala-namematching-service={{ ala_namematching_service_version }}
    state: present
    autoclean: yes
    update_cache: yes
    force: yes
  tags:
    - apt

# See:
# https://github.com/ansible/ansible/issues/29352
# https://github.com/ansible/ansible/pull/39794
# https://github.com/ansible/ansible/pull/74196
- name: dpkg-reconfigure to get rid of configuration changes
  shell: "dpkg-reconfigure -f noninteractive {{ item }}"
  with_items:
    - ala-namematching-service
  tags:
    - apt

#NBN need to install custom JAR file over the top of version installed by apt - we should look at making our own package
#The following is copied form exec-jar task
- name: Set if NBN version
  set_fact:
    namematching_is_nbn: namematching_service_overlay_version is defined

- name: Install dependencies for ansible python 2
  apt:
    name: python-lxml
    state: present
  when: ansible_python.version.major==2 and namematching_is_nbn
  tags:
    - service

- name: Install dependencies for ansible python 3
  apt:
    name: python3-lxml
    state: present
  when: ansible_python.version.major==3 and namematching_is_nbn
  tags:
    - service

- name: "Download ala-namematching-service JAR"
  maven_artifact:
    group_id: "{{groupId}}"
    artifact_id: "{{artifactId}}"
    version: "{{namematching_service_overlay_version}}"
    extension: "{{packaging|default('jar')}}"
    classifier: "{{classifier|default('')}}"
    repository_url: "{{maven_repo_url}}"
    timeout: 30
    dest: "/opt/atlas/ala-namematching-service/{{artifactId}}.jar"
    mode: u=rwx,g=rx,o=rx
    owner: namematching
    group: namematching
    verify_checksum: always
  notify: "restart ala-namematching-service"
  when: namematching_is_nbn
  tags:
    - namematching-service
    - deploy
    - service

- name: Start service ala-namematching-service installed via apt, if not running
  service:
    name: ala-namematching-service
    state: started
  tags:
    - apt
  when:
    - skip_handlers | default("false") | bool == false
