- include: ../../common/tasks/setfacts.yml
  tags:
    - namematching-service
    - deploy
    - properties
    - nginx_vhost

- include: ./apt.yml
  when: namematching_service_version is defined and namematching_service_version is not search("-NBN")
  tags:
    - namematching-service
    - deploy
    - apt

#NBN need to install custom JAR file over the top of version installed by apt - first install with ala version then set the nbn version and run again
#The following is copied form exec-jar task
- name: Update apt
  apt:
    update_cache: yes
  tags:
    - service

- name: Install dependencies for ansible python 2
  apt:
    name: python-lxml
    state: present
  when: ansible_python.version.major==2
  tags:
    - service

- name: Install dependencies for ansible python 3
  apt:
    name: python3-lxml
    state: present
  when: ansible_python.version.major==3
  tags:
    - service

- name: "Download ala-namematching-service JAR"
  maven_artifact:
    group_id: "{{groupId}}"
    artifact_id: "{{artifactId}}"
    version: "{{namematching_service_version}}"
    extension: "{{packaging|default('jar')}}"
    classifier: "{{classifier|default('')}}"
    repository_url: "{{maven_repo_url}}"
    timeout: 30
    dest: "/opt/atlas/ala-namematching-service/{{artifactId}}.jar"
    mode: u=rwx,g=rx,o=rx
    owner: namematching
    group: namematching
    verify_checksum: always
  notify: "restart ala-namematching-service"
  when: namematching_service_version is defined and namematching_service_version is search("-NBN")
  tags:
    - namematching-service
    - deploy
    - service

- name: Customize configuration already added by apt package
  template:
    src: namematching-service-config.yml
    dest: "{{data_dir}}/ala-namematching-service/config/config.yml"
    owner: "{{ namematching_user }}"
    group: "{{ namematching_user }}"
  notify:
    - restart ala-namematching-service
  tags:
    - properties
    - namematching-service

- name: "Create ala-namematching-service directories"
  file:
    path: "{{item}}"
    state: directory
    owner: "{{ namematching_user }}"
    group: "{{ namematching_user }}"
    mode: 0755
  with_items:
    - "/var/log/atlas/namematching-service"
  tags:
    - properties
    - namematching-service

- name: Customize species group files
  copy:
    src: "{{item}}"
    dest: "{{data_dir}}/ala-namematching-service/config/{{item}}"
    owner: "{{ namematching_user }}"
    group: "{{ namematching_user }}"
  with_items:
    - "groups.json"
    - "subgroups.json"
  notify:
    - restart ala-namematching-service
  tags:
    - properties
    - namematching-service

- name: Disable previous namematching service (not packaged war)
  service:
    name: namematching-service
    state: stopped
    enabled: no
  ignore_errors: yes

- name: add nginx vhost
  include_role:
    name: nginx_vhost
  vars:
    appname: "namematching-service"
    hostname: "{{ namematching_service_hostname }}"
    context_path: "{{ namematching_service_context_path }}"
    nginx_paths:
      - path: "{{ namematching_service_context_path }}"
        is_proxy: true
        proxy_pass: "http://127.0.0.1:{{ namematching_service_port }}/{{ namematching_service_context_path }}"
  # notify:
  #   - reload nginx
  tags:
    - nginx_vhost
    - namematching-service
    - deploy
  when: webserver_nginx
