---

- include: ./apt.yml
  when: namematching_service_version is defined and namematching_service_version is not search("-NBN")
  tags:
    - namematching-service
    - deploy
    - apt

#NBN need to install custom JAR file over the top of version installed by apt - first install with ala version then set the nbn version and run again
#The following is copied form exec-jar task
- name: Update apt
  apt:
    update_cache: yes
  tags:
    - service

- name: Install dependencies for ansible python 2
  apt:
    name: python-lxml
    state: present
  when: ansible_python.version.major==2
  tags:
    - service

- name: Install dependencies for ansible python 3
  apt:
    name: python3-lxml
    state: present
  when: ansible_python.version.major==3
  tags:
    - service

- name: "Download ala-namematching-service JAR"
  maven_artifact:
    group_id: "{{groupId}}"
    artifact_id: "{{artifactId}}"
    version: "{{namematching_service_version}}"
    extension: "{{packaging|default('jar')}}"
    classifier: "{{classifier|default('')}}"
    repository_url: "{{maven_repo_url}}"
    timeout: 30
    dest: "/opt/atlas/ala-namematching-service/{{artifactId}}.jar"
    mode: u=rwx,g=rx,o=rx
    owner: namematching
    group: namematching
    verify_checksum: always
  notify: "restart ala-namematching-service"
  when: namematching_service_version is defined and namematching_service_version is search("-NBN")
  tags:
    - namematching-service
    - deploy
    - service

- name: Disable previous namematching service (not packaged war)
  service:
    name: namematching-service
    state: stopped
    enabled: false
  ignore_errors: true

- name: delete the current names index /data/lucene/namematching-nm.tgz
  ansible.builtin.file:
    path: /data/lucene/namematching-nm.tgz
    state: absent
  tags:
    - nameindex

- name: delete the current names index unpacked /data/lucene/namematching-nm
  ansible.builtin.file:
    path: /data/lucene/namematching-nm
    state: absent
  tags:
    - nameindex

- name: install the names index {{ ala_namemaching_service_source | default('https://archives.ala.org.au/archives/nameindexes/20210811/namematching-20210811.tgz') }}
  import_tasks: ./download-nameindex.yml
  vars:
    dest: "/data/lucene/namematching-nm.tgz"
    final_dest: "/data/lucene/namematching-nm/"
    url: "{{ ala_namemaching_service_source | default('https://archives.ala.org.au/archives/nameindexes/20210811/namematching-20210811.tgz') }}"
    sha1: "{{ ala_namemaching_service_source_sha1 | default('563814a7b5d886b746e10eb40c44f0d9bda62371') }}"
  notify:
    - restart ala-namematching-service
  tags:
    - nameindex
