- hosts: solr7-server
  roles:
    - common
    - java
    # this is to allow for toolkit using solr7-standalone
    - { role: solr7, when: "solr_version is version('8', '<')" }
    - { role: solr8, when: "solr_version is  version('8.1.0', '>=')" }
